# Plugin configuration
debug: true

rewardMultiplier: 1.5
# {player} {uuid} {score} {multiplier_score}
rewardCommands:
  - "say Congratulations to {player}! You scored {score} points!, earning a total of {multiplier_score} points!"

gameLength: 20
baseDespawnTicks: 100
minDespawnTicks: 40
# Despawn speed is baseDespawnTicks - (score * despawnMultiplier)
despawnMultiplier: 3
# Spawning speed is internally calculated


message_prefix: "<blue>[ FShootingGame ]</blue>"
start_message: "<green>The game has started!"
gameover_message: "<red>Game Over! Your score: <score>"
already_running: "<red>A game is already running!"


spawnPoints:
  - world: world
    x: 100.5
    y: 64.0
    z: -200.5
    yaw: 0.0
    pitch: 0.0
  - world: world
    x: -150.5
    y: 70.0
    z: 300.5
    yaw: 90.0
    pitch: 0.0