# Plugin configuration

debug: true

rewardMultiplier: 1.5
rewardCommands:
  - "give %player% diamond %rewardAmount%"

spawnPoints:
  - world: world
    x: 100.5
    y: 64.0
    z: -200.5
    yaw: 0.0
    pitch: 0.0
  - world: world
    x: -150.5
    y: 70.0
    z: 300.5
    yaw: 90.0
    pitch: 0.0